// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu_trace.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cpu_5ftrace_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cpu_5ftrace_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cpu_5ftrace_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cpu_5ftrace_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cpu_5ftrace_2eproto;
namespace CPUTrace {
class MicroOp;
class MicroOpDefaultTypeInternal;
extern MicroOpDefaultTypeInternal _MicroOp_default_instance_;
class TraceFile;
class TraceFileDefaultTypeInternal;
extern TraceFileDefaultTypeInternal _TraceFile_default_instance_;
}  // namespace CPUTrace
PROTOBUF_NAMESPACE_OPEN
template<> ::CPUTrace::MicroOp* Arena::CreateMaybeMessage<::CPUTrace::MicroOp>(Arena*);
template<> ::CPUTrace::TraceFile* Arena::CreateMaybeMessage<::CPUTrace::TraceFile>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace CPUTrace {

enum MicroOp_Operation : int {
  MicroOp_Operation_EXE = 0,
  MicroOp_Operation_LOAD = 1,
  MicroOp_Operation_STORE = 2,
  MicroOp_Operation_MicroOp_Operation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MicroOp_Operation_MicroOp_Operation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool MicroOp_Operation_IsValid(int value);
constexpr MicroOp_Operation MicroOp_Operation_Operation_MIN = MicroOp_Operation_EXE;
constexpr MicroOp_Operation MicroOp_Operation_Operation_MAX = MicroOp_Operation_STORE;
constexpr int MicroOp_Operation_Operation_ARRAYSIZE = MicroOp_Operation_Operation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MicroOp_Operation_descriptor();
template<typename T>
inline const std::string& MicroOp_Operation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MicroOp_Operation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MicroOp_Operation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MicroOp_Operation_descriptor(), enum_t_value);
}
inline bool MicroOp_Operation_Parse(
    const std::string& name, MicroOp_Operation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MicroOp_Operation>(
    MicroOp_Operation_descriptor(), name, value);
}
// ===================================================================

class TraceFile :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CPUTrace.TraceFile) */ {
 public:
  TraceFile();
  virtual ~TraceFile();

  TraceFile(const TraceFile& from);
  TraceFile(TraceFile&& from) noexcept
    : TraceFile() {
    *this = ::std::move(from);
  }

  inline TraceFile& operator=(const TraceFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline TraceFile& operator=(TraceFile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TraceFile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TraceFile* internal_default_instance() {
    return reinterpret_cast<const TraceFile*>(
               &_TraceFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TraceFile* other);
  friend void swap(TraceFile& a, TraceFile& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TraceFile* New() const final {
    return CreateMaybeMessage<TraceFile>(nullptr);
  }

  TraceFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TraceFile>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TraceFile& from);
  void MergeFrom(const TraceFile& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TraceFile* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CPUTrace.TraceFile";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cpu_5ftrace_2eproto);
    return ::descriptor_table_cpu_5ftrace_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CPUTrace.MicroOp micro_ops = 4;
  int micro_ops_size() const;
  void clear_micro_ops();
  static const int kMicroOpsFieldNumber = 4;
  ::CPUTrace::MicroOp* mutable_micro_ops(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPUTrace::MicroOp >*
      mutable_micro_ops();
  const ::CPUTrace::MicroOp& micro_ops(int index) const;
  ::CPUTrace::MicroOp* add_micro_ops();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPUTrace::MicroOp >&
      micro_ops() const;

  // uint64 start = 1;
  void clear_start();
  static const int kStartFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 start() const;
  void set_start(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 end = 2;
  void clear_end();
  static const int kEndFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint64 end() const;
  void set_end(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 num_micro_ops = 3;
  void clear_num_micro_ops();
  static const int kNumMicroOpsFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::uint64 num_micro_ops() const;
  void set_num_micro_ops(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:CPUTrace.TraceFile)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPUTrace::MicroOp > micro_ops_;
  ::PROTOBUF_NAMESPACE_ID::uint64 start_;
  ::PROTOBUF_NAMESPACE_ID::uint64 end_;
  ::PROTOBUF_NAMESPACE_ID::uint64 num_micro_ops_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cpu_5ftrace_2eproto;
};
// -------------------------------------------------------------------

class MicroOp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CPUTrace.MicroOp) */ {
 public:
  MicroOp();
  virtual ~MicroOp();

  MicroOp(const MicroOp& from);
  MicroOp(MicroOp&& from) noexcept
    : MicroOp() {
    *this = ::std::move(from);
  }

  inline MicroOp& operator=(const MicroOp& from) {
    CopyFrom(from);
    return *this;
  }
  inline MicroOp& operator=(MicroOp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MicroOp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MicroOp* internal_default_instance() {
    return reinterpret_cast<const MicroOp*>(
               &_MicroOp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MicroOp* other);
  friend void swap(MicroOp& a, MicroOp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MicroOp* New() const final {
    return CreateMaybeMessage<MicroOp>(nullptr);
  }

  MicroOp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MicroOp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MicroOp& from);
  void MergeFrom(const MicroOp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MicroOp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CPUTrace.MicroOp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cpu_5ftrace_2eproto);
    return ::descriptor_table_cpu_5ftrace_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef MicroOp_Operation Operation;
  static constexpr Operation EXE =
    MicroOp_Operation_EXE;
  static constexpr Operation LOAD =
    MicroOp_Operation_LOAD;
  static constexpr Operation STORE =
    MicroOp_Operation_STORE;
  static inline bool Operation_IsValid(int value) {
    return MicroOp_Operation_IsValid(value);
  }
  static constexpr Operation Operation_MIN =
    MicroOp_Operation_Operation_MIN;
  static constexpr Operation Operation_MAX =
    MicroOp_Operation_Operation_MAX;
  static constexpr int Operation_ARRAYSIZE =
    MicroOp_Operation_Operation_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Operation_descriptor() {
    return MicroOp_Operation_descriptor();
  }
  template<typename T>
  static inline const std::string& Operation_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Operation>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Operation_Name.");
    return MicroOp_Operation_Name(enum_t_value);
  }
  static inline bool Operation_Parse(const std::string& name,
      Operation* value) {
    return MicroOp_Operation_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint64 eip = 1;
  void clear_eip();
  static const int kEipFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 eip() const;
  void set_eip(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 load_or_store_addr = 3;
  void clear_load_or_store_addr();
  static const int kLoadOrStoreAddrFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::uint64 load_or_store_addr() const;
  void set_load_or_store_addr(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 size = 4;
  void clear_size();
  static const int kSizeFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::uint64 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // .CPUTrace.MicroOp.Operation opr = 2;
  void clear_opr();
  static const int kOprFieldNumber = 2;
  ::CPUTrace::MicroOp_Operation opr() const;
  void set_opr(::CPUTrace::MicroOp_Operation value);

  // @@protoc_insertion_point(class_scope:CPUTrace.MicroOp)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 eip_;
  ::PROTOBUF_NAMESPACE_ID::uint64 load_or_store_addr_;
  ::PROTOBUF_NAMESPACE_ID::uint64 size_;
  int opr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cpu_5ftrace_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TraceFile

// uint64 start = 1;
inline void TraceFile::clear_start() {
  start_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TraceFile::start() const {
  // @@protoc_insertion_point(field_get:CPUTrace.TraceFile.start)
  return start_;
}
inline void TraceFile::set_start(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  start_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.TraceFile.start)
}

// uint64 end = 2;
inline void TraceFile::clear_end() {
  end_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TraceFile::end() const {
  // @@protoc_insertion_point(field_get:CPUTrace.TraceFile.end)
  return end_;
}
inline void TraceFile::set_end(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  end_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.TraceFile.end)
}

// uint64 num_micro_ops = 3;
inline void TraceFile::clear_num_micro_ops() {
  num_micro_ops_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 TraceFile::num_micro_ops() const {
  // @@protoc_insertion_point(field_get:CPUTrace.TraceFile.num_micro_ops)
  return num_micro_ops_;
}
inline void TraceFile::set_num_micro_ops(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  num_micro_ops_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.TraceFile.num_micro_ops)
}

// repeated .CPUTrace.MicroOp micro_ops = 4;
inline int TraceFile::micro_ops_size() const {
  return micro_ops_.size();
}
inline void TraceFile::clear_micro_ops() {
  micro_ops_.Clear();
}
inline ::CPUTrace::MicroOp* TraceFile::mutable_micro_ops(int index) {
  // @@protoc_insertion_point(field_mutable:CPUTrace.TraceFile.micro_ops)
  return micro_ops_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPUTrace::MicroOp >*
TraceFile::mutable_micro_ops() {
  // @@protoc_insertion_point(field_mutable_list:CPUTrace.TraceFile.micro_ops)
  return &micro_ops_;
}
inline const ::CPUTrace::MicroOp& TraceFile::micro_ops(int index) const {
  // @@protoc_insertion_point(field_get:CPUTrace.TraceFile.micro_ops)
  return micro_ops_.Get(index);
}
inline ::CPUTrace::MicroOp* TraceFile::add_micro_ops() {
  // @@protoc_insertion_point(field_add:CPUTrace.TraceFile.micro_ops)
  return micro_ops_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CPUTrace::MicroOp >&
TraceFile::micro_ops() const {
  // @@protoc_insertion_point(field_list:CPUTrace.TraceFile.micro_ops)
  return micro_ops_;
}

// -------------------------------------------------------------------

// MicroOp

// uint64 eip = 1;
inline void MicroOp::clear_eip() {
  eip_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MicroOp::eip() const {
  // @@protoc_insertion_point(field_get:CPUTrace.MicroOp.eip)
  return eip_;
}
inline void MicroOp::set_eip(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  eip_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.MicroOp.eip)
}

// .CPUTrace.MicroOp.Operation opr = 2;
inline void MicroOp::clear_opr() {
  opr_ = 0;
}
inline ::CPUTrace::MicroOp_Operation MicroOp::opr() const {
  // @@protoc_insertion_point(field_get:CPUTrace.MicroOp.opr)
  return static_cast< ::CPUTrace::MicroOp_Operation >(opr_);
}
inline void MicroOp::set_opr(::CPUTrace::MicroOp_Operation value) {
  
  opr_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.MicroOp.opr)
}

// uint64 load_or_store_addr = 3;
inline void MicroOp::clear_load_or_store_addr() {
  load_or_store_addr_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MicroOp::load_or_store_addr() const {
  // @@protoc_insertion_point(field_get:CPUTrace.MicroOp.load_or_store_addr)
  return load_or_store_addr_;
}
inline void MicroOp::set_load_or_store_addr(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  load_or_store_addr_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.MicroOp.load_or_store_addr)
}

// uint64 size = 4;
inline void MicroOp::clear_size() {
  size_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MicroOp::size() const {
  // @@protoc_insertion_point(field_get:CPUTrace.MicroOp.size)
  return size_;
}
inline void MicroOp::set_size(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:CPUTrace.MicroOp.size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CPUTrace

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::CPUTrace::MicroOp_Operation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CPUTrace::MicroOp_Operation>() {
  return ::CPUTrace::MicroOp_Operation_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cpu_5ftrace_2eproto
